[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "unieinfra"
authors = [{name = "UnieAI", email = "contact@unieai.com"}]
dynamic = ["version", "description"]
